from __future__ import annotations

from .schemas import MemoryCandidate, SieveDecision, MemoryEvent, new_id


class PolicyGovernor:
    """
    Python enforcement layer.

    Gemma Sieve Brain recommends memory consequences.
    The governor enforces hard invariants so the framework remains safe and testable.

    Key v1 invariant added here:
    - Brain-1 generated claims / interpretations are not automatically authoritative truth.
      If Gemma marks them active/fossil, the governor downgrades them to non_authoritative
      unless they are represented as deterministic observations elsewhere.
    """

    def validate(
        self,
        *,
        task_id: str,
        candidates: list[MemoryCandidate],
        decisions: list[SieveDecision],
    ) -> list[MemoryEvent]:
        candidate_by_id = {c.candidate_id: c for c in candidates}
        events: list[MemoryEvent] = []

        for decision in decisions:
            candidate = candidate_by_id.get(decision.candidate_id)
            if candidate is None:
                continue

            notes: list[str] = []
            self._enforce_claim_authority_invariant(candidate, decision, notes)
            self._enforce_proxy_invariant(candidate, decision, notes)
            self._enforce_invalidated_invariant(candidate, decision, notes)
            self._enforce_payload_invariant(candidate, decision, notes)
            self._enforce_artifact_invariant(candidate, decision, notes)
            self._enforce_caveat_invariant(candidate, decision, notes)
            self._enforce_alias_learning_invariant(candidate, decision, notes)

            events.append(MemoryEvent(
                event_id=new_id("event"),
                task_id=task_id,
                candidate=candidate,
                decision=decision,
                governor_notes=notes,
            ))

        return events

    def _enforce_claim_authority_invariant(
        self,
        candidate: MemoryCandidate,
        decision: SieveDecision,
        notes: list[str],
    ) -> None:
        """
        Generic authority rule.

        Claims and interpretations generated by Brain 1 are useful memory, but they
        should not enter future context as settled truth. They can be carried as
        non-authoritative task-agent claims, with evidence refs available for audit.

        This is intentionally domain-neutral:
        - medical: model says tumor progression
        - finance: model says stock is overvalued
        - code: model says root cause is race condition
        - legal: model says clause is likely unenforceable
        All are interpretations unless separately validated.
        """
        if candidate.candidate_type not in {"claims", "interpretations"}:
            return

        if candidate.source_type not in {"task_answer", "sieve_brain"}:
            return

        if decision.status not in {"active", "fossil"}:
            return

        original_text = decision.carry_text or candidate.content
        decision.status = "non_authoritative"
        decision.carry_text = (
            "Task-agent claim/interpretation, non-authoritative unless revalidated: "
            + self._compact(original_text, max_chars=550)
        )
        decision.kv_future_hint = "do_not_fossilize"
        decision.reason = (
            decision.reason
            + " Governor override: Brain-1 generated claims/interpretations must not become authoritative active truth without separate validation."
        )
        notes.append("Downgraded task-answer claim/interpretation to non_authoritative.")

    def _enforce_proxy_invariant(
        self,
        candidate: MemoryCandidate,
        decision: SieveDecision,
        notes: list[str],
    ) -> None:
        if candidate.metadata.get("proxy_risk"):
            if decision.status in {"fossil", "active"}:
                decision.status = "non_authoritative"
                decision.carry_text = (
                    decision.carry_text
                    or "Proxy risk detected: this result must not be treated as authoritative for the original requested task."
                )
                decision.kv_future_hint = "block_truth"
                notes.append("Overrode proxy-risk candidate to non_authoritative.")

    def _enforce_invalidated_invariant(
        self,
        candidate: MemoryCandidate,
        decision: SieveDecision,
        notes: list[str],
    ) -> None:
        content_l = candidate.content.lower()
        if "invalidated" in content_l or "must not be treated as true" in content_l:
            if decision.status == "fossil":
                decision.status = "invalidated"
                decision.carry_text = decision.carry_text or candidate.content[:400]
                decision.kv_future_hint = "block_truth"
                notes.append("Overrode invalidation-like candidate away from fossil.")

    def _enforce_payload_invariant(
        self,
        candidate: MemoryCandidate,
        decision: SieveDecision,
        notes: list[str],
    ) -> None:
        # Large raw payload should not become active context.
        if candidate.candidate_type == "tool_outputs" and (candidate.token_cost or 0) > 800:
            if decision.status in {"fossil", "active"}:
                decision.status = "archived"
                decision.carry_text = None
                decision.kv_future_hint = "external_only"
                notes.append("Large raw tool output was forced to archived/external-only.")

    def _enforce_artifact_invariant(
        self,
        candidate: MemoryCandidate,
        decision: SieveDecision,
        notes: list[str],
    ) -> None:
        # Artifact references are important evidence but should usually stay in archive.
        if candidate.candidate_type == "artifacts":
            if decision.status == "fossil":
                decision.status = "archived"
                decision.carry_text = None
                decision.kv_future_hint = "external_only"
                notes.append("Artifact path was forced from fossil to archived.")

    def _enforce_caveat_invariant(
        self,
        candidate: MemoryCandidate,
        decision: SieveDecision,
        notes: list[str],
    ) -> None:
        if candidate.candidate_type == "caveats":
            # Caveats are allowed to survive. If Gemma decays them, keep at least active
            # when risk is high.
            if (candidate.risk_if_wrong or 0) >= 3 and decision.status in {"decay", "archived"}:
                decision.status = "active"
                decision.carry_text = decision.carry_text or candidate.content[:500]
                decision.kv_future_hint = "keep_until_claim_resolved"
                notes.append("High-risk caveat was promoted to active.")

    def _enforce_alias_learning_invariant(
        self,
        candidate: MemoryCandidate,
        decision: SieveDecision,
        notes: list[str],
    ) -> None:
        if candidate.metadata.get("learning_type") == "alias_normalization":
            if decision.status not in {"fossil", "active"}:
                decision.status = "fossil"
                decision.carry_text = decision.carry_text or candidate.content
                decision.kv_future_hint = "protected_reanchor"
                notes.append("Validated alias learning was promoted to fossil.")

    def required_cautions_from_events(self, events: list[MemoryEvent]) -> list[str]:
        cautions: list[str] = []
        for event in events:
            status = event.decision.status
            ctype = event.candidate.candidate_type
            if status == "non_authoritative":
                cautions.append(event.decision.carry_text or event.candidate.content[:500])
            elif ctype == "caveats" and status in {"active", "fossil"}:
                cautions.append(event.decision.carry_text or event.candidate.content[:500])
        return self._dedupe(cautions)

    @staticmethod
    def _compact(text: str, max_chars: int = 550) -> str:
        clean = " ".join(str(text).split())
        if len(clean) > max_chars:
            return clean[:max_chars] + "...[truncated]"
        return clean

    @staticmethod
    def _dedupe(items: list[str]) -> list[str]:
        seen: set[str] = set()
        out: list[str] = []
        for item in items:
            clean = " ".join(str(item).split())
            if clean and clean not in seen:
                seen.add(clean)
                out.append(clean)
        return out
